#!/usr/bin/env node
// 法務案件管理スプシのデータを legal_cases テーブルに移行
// 使い方: node scripts/legal-import.js [team_id]
//   team_id 省略時は process.env.LEGAL_IMPORT_TEAM_ID
//   既存案件（同名）はスキップ（重複防止）

require('dotenv').config();
const { dbQuery } = require('../src/db/index');

const TEAM_ID = process.argv[2] || process.env.LEGAL_IMPORT_TEAM_ID || 'T086C06L5V0';

// 日本語日付 → YYYY-MM-DD（"6月19日" → 2026-06-19、参照年は今年）
function parseJpDate(s) {
  if (!s) return null;
  const t = String(s).trim();
  if (!t || t === 'ー' || t === '-' || t === '−') return null;
  const m = t.match(/^(\d{1,2})月(\d{1,2})日$/);
  if (m) {
    const y = new Date().getFullYear();
    return `${y}-${String(m[1]).padStart(2,'0')}-${String(m[2]).padStart(2,'0')}`;
  }
  // 2026/04/02 形式
  const m2 = t.match(/^(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})$/);
  if (m2) return `${m2[1]}-${String(m2[2]).padStart(2,'0')}-${String(m2[3]).padStart(2,'0')}`;
  return null;
}

// スプシの45件（NO/案件名/NA日/担当/ステータス/ボール/NA台帳/問題該当箇所/契約書箇所/方向性/現状/処理台帳/契約書/スレッドURL/メール履歴/MTG議事録/結果/クローズ日）
const CASES = [
  { case_name:'NSSスマートコンサルティング株式会社', na_date:null, chief:'柳川', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行でクローズ', issue_details:'・本業務の遂行に必要な情報提供が適時になされていない ・催促や警告を受けても、対応遅延が複数回継続している ・期限遵守が不十分で、先方自身が示した回答予定も守られていない ・個別連絡の有無にかかわらず、依頼事項への実対応が滞っている ・その結果、円滑な業務遂行に必要な協力義務を欠く状態が生じている', contract_details:'第１０条第４項第２号 第１０条第４項第６号', direction:'返金保証外を落としどころとする。', current_state:'・柳川さんFACT回収中 メール送信（20260318） →メールの返信なし（20260325） 地藤さんあて書面到着、メールの返信がないため法務対応となる。交渉人ケースクローズ。', ledger_url:'こちらから確認', contract_url:'https://drive.google.com/file/d/1wDEufyLH8wtBU8h3m6uUPei1DOTTmPvC/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A71D5BWDV/p1769654427274449', email_slack_url:'https://docs.google.com/document/d/1VKWE5orS0Lb9C5KTaYfiaCmzdm_fRHNCB2C9f8TtJ5M/edit?tab=t.0', minutes_url:'', final_result:'法務移行', closed_date:'2026/04/02' },
  { case_name:'株式会社買取王国', na_date:'6月19日', chief:'柳川', status_phase:'再発注', ball:'クライアント', na_ledger:'・メール返信済み ・金曜日（４月24日）に野村さんと擦り合わせ→４月３０日に再見積もり依頼済み ５月１２日野村さんに進捗確認済み→催促するとのこと。 5月19日現在動きなし。野村さんに進捗確認を検討したい。 野村さんがヒアリングシート回収し、野村さんが見積もり作成中(0520) ・媒体を先方、 ありがとうございます！ キミスカの既得権保持させていただいて、キミスカより再度連絡ありましたら野村さん・志摩さんにご相談させていただきます！（買取王国様が急かして来たら連絡くるかな？） 地藤さんから野村さんに催促(0526)と見せかけて志摩から督促→5月25日夜にヒアリングシート回収できたため、これから見積もりの作成に移るとのこと→督促予定(0529)→野村さんから買取王国さんに見積もり提案しMTGセットしている模様で現在日程調整中(0604)→野村さんMTG月額で再見積もり予定(0611)', issue_details:'・契約上の必須条件にない基準で不採用を行っている（年齢・外国籍） ・合意した選考基準と実運用の選考基準が乖離している ・採用保証の前提である「条件に基づく選考」が崩れている', contract_details:'第１０条第４項第２号 第１０条第４項第７号', direction:'新卒は返金だが中途は返金対象外、しかし相殺事案と思料されるため左記カードをもとに、契約の再締結に抱き合わせて新卒はお願いベースとはなるが役務の提供の継続を打診する方向性が理想。', current_state:'打合せ日程決定：3月24日（火）1200 先方がこちらの打診内容を月内を目途に検討。再度MTGの設定となった。 再度MTG実施(４月６日)→中途は再見積もり後、再発注の意向あり、新卒は返金か？今後再度提案資料を作成し、提案する予定', ledger_url:'こちらから確認', contract_url:'▼中途 https://drive.google.com/file/d/1bY_tSgCjfIV5cXodGThI7iv6IqIaUzvQ/view?usp=sharing  ▼新卒 https://drive.google.com/file/d/1T2PouUmEd8V6YagBM3uuXwqg6dIBfjyx/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1772499426368809?thread_ts=1770973758.390899&cid=C0A3AGJBNF6', email_slack_url:'https://docs.google.com/document/d/1JiPJypOmonGoQtnqNSqvjkiHGlpuZTTJXC69xqzvZzw/edit?tab=t.0', minutes_url:'', final_result:'▼中途 返金→再発注（予定）  ▼新卒 返金（5月請求／6月支払い）', closed_date:null },
  { case_name:'株式会社ゴルディロックス', na_date:null, chief:'土井', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行でクローズ', issue_details:'', contract_details:'', direction:'', current_state:'法務対応', ledger_url:'', contract_url:'https://drive.google.com/file/d/1bAnwY5fxVi9GeOHkqvPR_V9MkXOFZS97/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1771481420171389', email_slack_url:'', minutes_url:'', final_result:'法務移行', closed_date:'2026/04/22' },
  { case_name:'株式会社リハビタブル', na_date:null, chief:'土井', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行でクローズ', issue_details:'', contract_details:'', direction:'', current_state:'法務対応', ledger_url:'', contract_url:'https://drive.google.com/file/d/1rO0e3F66UtPz0TaHtVFunh5xIA-oN-63/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1771571626058299', email_slack_url:'', minutes_url:'', final_result:'法務移行', closed_date:'2026/04/22' },
  { case_name:'株式会社アスタリスク', na_date:null, chief:'土井', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行でクローズ', issue_details:'○必須条件外 ○非協力的な姿勢[12:38]○不合格理由を教えてもらえないという非協力的な姿勢 →採用戦略の分析もできなければ、対応も難しい', contract_details:'・第10条4項の2 ・第10条4項の4', direction:'', current_state:'メール文案作成中 送信後、返答あり(４月９日)、顧問弁護士を通じ書面にて正式回答とのこと、交渉人対応クローズか？', ledger_url:'', contract_url:'https://drive.google.com/file/d/1BYkuMCW89jUcAdYoVZp5NuefSEwEEOr-/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1771296131802829', email_slack_url:'https://docs.google.com/document/d/1cnTMHc6CxjSXzEXoLI2w5DzdT_FVGjN4i5LetyQtQwI/edit?tab=t.0', minutes_url:'', final_result:'法務移行 ※内容証明が届いた', closed_date:'2026/04/23' },
  { case_name:'株式会社タイズ', na_date:null, chief:'柳川', status_phase:'法務移行', ball:'完了', na_ledger:'返金対象外でクローズ', issue_details:'・契約上のMUST条件にない理由で不採用を実施している ・選考基準が契約内容と乖離している（後出しで基準を厳格化） ・定性的・追加的な基準で母集団を毀損している ・結果として採用保証の前提条件を満たしていない', contract_details:'第１０条第４項第２号 第１０条第４項第７号', direction:'', current_state:'・メール送信（20260327） ・4月７日MTG', ledger_url:'', contract_url:'https://drive.google.com/file/d/19Q66pdCk1Vak0IQNFnp7LUxNdF2z3mlh/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1771482682224209', email_slack_url:'https://docs.google.com/document/d/1idlSRr97HrJyxS19ZlkwUzWDpZlvEIPPxfqZYPytFsg/edit?tab=t.0', minutes_url:'', final_result:'対象外了承', closed_date:'2026/04/15' },
  { case_name:'オーガニックグループ株式会社', na_date:'6月12日', chief:'柳川', status_phase:'CL交渉中', ball:'INREVO', na_ledger:'MTG日程を打診済み→先方より返事待ち(５月１１日)  5月21日10時からMTGセット済み→MTG実施済み基本方針は返金対象外、しかし、先方との協議で月額充当もしくは返金後再発注の線も残存。最終見解を5月２８日までに相手に送付しないといけない。 野村さんに月額金額を依頼予定(0526)、ヒアリングシート送付も送付予定。 野村さんに月額と、ヒアリングシート依頼済み(0526)→ヒアリングシート回収→メール文案作成予定→0527先方にヒアリング項目及び見解を送付済み→メール返信あり(0603)返信文案考案中→一次返信(0605)→文案決裁中(0611)', issue_details:'• 畔津 美咲様：転職軸が「わくわく・楽しそう」という点で弱く、回答に一貫性がないことに加え、話が結論まで長いといったコミュニケーション上の懸念を理由に見送り。 • 藤野 智大様：キャリアに一貫性や明確な軸がなく、弊社で中長期的に活躍するイメージが湧かないという理由で不合格。 • 三倉 妃奈様：スキルセットに問題はないものの、短期・中期ビジョンがふわっとしていることや、外的要因によるモチベーション思考であることを理由に、成果・業務遂行への不安から見送り。', contract_details:'・サービス利用規約第10条第4項第5号（契約締結後に新たに申し出た人材要件による見送り）', direction:'', current_state:'メール送信済み ４月１０日MTG  ・メールにてMTG打診（5月11日）', ledger_url:'処理台帳', contract_url:'▼Webマーケター https://drive.google.com/file/d/11h-3ZN-ZDHHCg_UUi2r7rNCLIhxMFxP5/view?usp=sharing  ▼不動産賃貸営業 https://drive.google.com/file/d/1nhxhUx5Ph9u4FyZKVUcVXTMmWngdXsnM/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A71D5BWDV/p1771472224793889', email_slack_url:'https://docs.google.com/document/d/1SxT7M_dFa_PDG9LFinPPmb5c7uIaMJMXnVtyN_TEbyg/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社ホンダ泉州販売', na_date:null, chief:'土井', status_phase:'返金クローズ', ball:'クライアント', na_ledger:'返金クローズ 先方より請求書発行待ち ※5月11日 請求書到着（5月17日） →社内展開完了 ※対応者：土井さん', issue_details:'・外国籍不可ではないにも関わらず、複数名にわたり不採用にしている。', contract_details:'・サービス利用規約第10条第4項第5号', direction:'', current_state:'▼中途採用 返金保証対象外に納得  ▼新卒採用 返金依頼  ▼先方への請求書発行依頼メールの確認中 ※5月11日 →OKであれば即日でメール →南さんからOK→メール送信済み', ledger_url:'', contract_url:'▼新卒 https://drive.google.com/file/d/1TIQ-uJezakB_Zf3bBuMgiorEQU0LTB_D/view?usp=sharing ▼中途 https://drive.google.com/file/d/1vuJjhVYuXl7xOzZoKfjwkW-2ad25iPWJ/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1772022845728559', email_slack_url:'https://docs.google.com/document/d/1SO0UhSBgMlcy79sfhSfLdMABuIovk6F5QzmCaqs-nsU/edit?tab=t.0', minutes_url:'', final_result:'▼中途 返金保証外決定  ▼新卒 返金', closed_date:'2026/06/30' },
  { case_name:'株式会社PORTE HOMME', na_date:null, chief:'柳川', status_phase:'返金クローズ', ball:'完了', na_ledger:'返金でクローズ', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1k-qRV4e4I4EV1sHPF2jQf_niJrJh5ZuX/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1772764468253899', email_slack_url:'', minutes_url:'', final_result:'返金でクローズ', closed_date:'2026/04/30' },
  { case_name:'有限会社生目緑地建設', na_date:null, chief:'土井', status_phase:'ステイ', ball:'完了', na_ledger:'代表レイヤー折衝のため、いったんステイ ↓ 3月22日でストップ https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1774444375434929?thread_ts=1768967412.729249&cid=C0A3AGJBNF6', issue_details:'依頼事項（媒体開設）に対する対応遅延（媒体開設）による採用活動、母集団形成に影響を及ぼしている。 【補足】オープンワークについては"キャンペーン適用条件として12月末までの申し込み"が定められており 11月末より案内・催促をしていたが間に合いませんでした。 現状、オープンワークの掲載はできておらず、最小戦略に大きな影響を及ぼしています。 ・求人より少ない年収を面接時に伝え、辞退をされている', contract_details:'第１０条第４項第２号', direction:'', current_state:'  南さん対応により、一旦沈静化（20260325）', ledger_url:'こちらから確認', contract_url:'https://drive.google.com/file/d/1Hmcx9WkUmWSn58Fbkqzvt0y9q829ukUM/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1768967412729249', email_slack_url:'', minutes_url:'', final_result:'支援継続', closed_date:null },
  { case_name:'株式会社四電工', na_date:null, chief:'柳川', status_phase:'見解案作成中', ball:'INREVO', na_ledger:'Chatwork注視→先方の弁護士からの受任通知到来したため、回答書案を山本先生に確認してもらっている(0601)', issue_details:'・カジュアル面談で選考をしている。', contract_details:'サービス規約第10条第4項4号および6号', direction:'27卒切替えの方向', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1A_dga8bLaTHjYIUL0TFm9gn-fkLVG8xY/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1768369953315249', email_slack_url:'', minutes_url:'', final_result:'27スライドに向けて調整中', closed_date:null },
  { case_name:'株式会社アバージェンス', na_date:null, chief:'西森', status_phase:'法務移行', ball:'完了', na_ledger:'メール送信（0428）法務対応でクローズ', issue_details:'・契約書外の理由で落としている。', contract_details:'・サービス利用規約第10条第4項第4号および第5号', direction:'・4月3日（金）に先方と打合せ完了 →一度社内で持ち帰り、メールにて通知を伝え済み', current_state:'・4月28日（火）にメール送信済み ※対象外であることは変わらないこと、メールをもって終了することを通知 ↓ 内容証明到着（0513）', ledger_url:'', contract_url:'https://drive.google.com/file/d/1dfH0D455MieQse8PQo-sZWvRF_UNQJj8/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1768993954737689', email_slack_url:'https://docs.google.com/document/d/1E6MdkJ6lxCTYy6VLdwA7IwBr6Y3CC2bq6gY9Bd0uetc/edit?tab=t.api0zhhluofx', minutes_url:'https://docs.google.com/document/d/1gx_A-noLG0ydkEKNAmQypYl1eTdmpnGntoAt41tm8ao/edit?tab=t.0', final_result:'法務移行', closed_date:'2026/05/13' },
  { case_name:'株式会社モデュレックス', na_date:null, chief:'西森', status_phase:'返金クローズ', ball:'完了', na_ledger:'返金でクローズ', issue_details:'事案①　定例MTGの依頼 10/28（火）に依頼した定例MTGの調整が再三連絡しているにも関わらず、11/27まで確定できなかった。  事案②　契約延長打診・媒体費立替への回答 1/22(木)におこなった提案、確認事項について現時点で回答いただけていない。', contract_details:'・「当社からの連絡に1週間以上応答がない場合」(弊社規約第10条第4項第1号) ・「委託業務の遂行にあたり協力的でない場合」(弊社規約第10条第4項第6号)', direction:'', current_state:'・メール送信済み（20260325） ・南さんと先方で電話の実施 https://inrevohq.slack.com/archives/C0AK52L5F35/p1774589718811839?thread_ts=1773140760.892969&cid=C0AK52L5F35', ledger_url:'', contract_url:'https://drive.google.com/file/d/1gRRwJ1XZhn7GmtBbfD-8eYVfYeDVCl5Z/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0AK52L5F35/p1773140760892969', email_slack_url:'https://docs.google.com/document/d/1wzb2o2JkGwlVVdC5GsZ3uQHEiw1cOilnV6wY640Zv4o/edit?tab=t.0', minutes_url:'', final_result:'法務移行', closed_date:null },
  { case_name:'株式会社LOTTE Hotel Arai', na_date:null, chief:'柳川', status_phase:'法務移行', ball:'完了', na_ledger:'法務確認後返金対象で帰結。クローズ', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1DMrQ6_0isTjf2BV1yodPTUCt8hBTJNSr/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A71D5BWDV/p1773881262710499', email_slack_url:'', minutes_url:'', final_result:'クローズ', closed_date:'2026/05/29' },
  { case_name:'株式会社ハイデイ日高', na_date:'6月12日', chief:'土井', status_phase:'社内相談中', ball:'INREVO', na_ledger:'平野共有済→メール送信済み →督促→5月15日lineで督促済み→５月２９日返信あり。回答案作成中→土井さんからAN依頼し、BIZOPS経由での調査結果をくれる想定。それ待ち(0602)', issue_details:'・後出しで外国籍NGとして不採用', contract_details:'・サービス利用規約第10条第4項第5号', direction:'', current_state:'○3月31日（火）13時～＠会議室A メール文案作成中→決裁後送信予定 ○先方より返事なし→催促の方向（5月11日） ※BCの藤原さんに電話ありなので、確認待ち', ledger_url:'', contract_url:'https://drive.google.com/file/d/1WvX3eEpADJCT69YAd_ol_qnnGVu3f_b4/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1770260787195849', email_slack_url:'https://docs.google.com/document/d/1xpxpecwcdPxLeCmhhE_tkn5xhjaBeJ8uWrdKHJJJx5Q/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'森松工業株式会社', na_date:null, chief:'土井', status_phase:'返金クローズ', ball:'完了', na_ledger:'返金のためクローズ', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1xAv9Ztvsn1Tx3zXTOPyjMytKPSza6_iH/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1770977887937759', email_slack_url:'', minutes_url:'', final_result:'返金でクローズ', closed_date:'2026/04/30' },
  { case_name:'株式会社フォロアス', na_date:null, chief:'土井', status_phase:'返金クローズ', ball:'完了', na_ledger:'土井さんにて請求書発行依頼済', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1LYSru3MlxE032y9977kIp94T_UJgtVd1/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1770286413605919', email_slack_url:'', minutes_url:'', final_result:'返金でクローズ', closed_date:'2026/04/30' },
  { case_name:'株式会社LUXURY', na_date:'6月19日', chief:'柳川', status_phase:'MTGセット', ball:'クライアント', na_ledger:'メール作成済み→社内確認中(5月12日)０５１３「延長する代わりに釘差し云々」のファクト確認のためのMTGをセット→0515 0515ＭＴＧ実施、新文案決裁中。→決裁完了送信予定(０５１８)→送信済み(0518) 返信あり。MTG日程調整に移る(0519)→日程調整メール送信済み05190915→MTGセット完了→5月25日16時～で確定 再度MTG希望されている。→MTGセットの進捗状況についてメール送付済み。(0527)→0602MTGセット完了。→7月30日の動画を編集し、先方提供かつMTGの設定にうつることで決定(0602)→6月19日14時から社外MTG(0603)', issue_details:'契約外の落とし', contract_details:'・第10条第4項第4号 →契約書不記載理由による不採用', direction:'', current_state:'・社名変更により延長打診ＮＧ', ledger_url:'', contract_url:'https://drive.google.com/file/d/1xAv9Ztvsn1Tx3zXTOPyjMytKPSza6_iH/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1775719241735209', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'ニッコーテクノ株式会社', na_date:null, chief:'', status_phase:'返金クローズ', ball:'完了', na_ledger:'進捗なし 柳川さんの方でスライド折衝中→５月末返金で着地', issue_details:'', contract_details:'', direction:'２６返金対応　２７受注で柳川さん折衝', current_state:'２６返金対応　２７受注で柳川さん折衝', ledger_url:'', contract_url:'▼新卒 https://drive.google.com/file/d/1GxmoIDlPIL6Tc7374tfJd1kvBtlErqa4/view?usp=sharing  ▼中途 https://drive.google.com/file/d/13t56zVkyMz-XV80ESgbsW8hhah2u6R4k/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'返金', closed_date:'2026/05/31' },
  { case_name:'株式会社ガーデン', na_date:null, chief:'柳川', status_phase:'見解送付済み', ball:'様子見', na_ledger:'・ANよりマイナビ転職の想定を回収次第、先方へ送る ↓ 社内確認中→法務対応フェーズでは現時点でないため、様子見に格下げ(0522) 0526→案件決裁で月額具体の決裁をとる。→平野さんから先方提案→文案作成済みの様子。 0527中のメール送付予定(平野さんから)', issue_details:'・使用不可媒体多数 ・メールアドレス作成遅延 ・募集しない地域やブランドもあり、契約書とは齟齬が発生している', contract_details:'サービス利用規約 ・第10条第3項第2号 ・第10条第3項第4号 ・第10条第3項第5号', direction:'・月額切替にて提案打診済み→理解は示している', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1qa8DWCqcrEGMEBpmx2nyc85sZHAGUjn9/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A00GASXHT/p1772687860235229', email_slack_url:'', minutes_url:'', final_result:'・月額提案済み（平野） →添田さん、長野さんで工数確認、月額金額決定', closed_date:null },
  { case_name:'株式会社クリケン', na_date:null, chief:'土井', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'メール送信済み', issue_details:'・契約内容ではない条件での不採用', contract_details:'サービス利用規約 ・第10条第4項第4号', direction:'レッドカード', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1adSHyjJYG-Bxf7HdOZeA_DcBQ4LaY2FR/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A71D5BWDV/p1775704528932229', email_slack_url:'https://docs.google.com/document/d/1bBw4UONyHXEPq7ZRONeuzm2nJUKrcCnqOB4fP7K48oE/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社イズミフードマシナリ', na_date:null, chief:'西森', status_phase:'対象外合意形成済み', ball:'完了', na_ledger:'返金対象外でクローズ。※支援継続 通知メール送信（5月11日済み） ↓ 先方からの反応待ち→5月19日現在の状況を西森さんに確認したところ、おそいものの対応はしてくれているとのこと。 0520返信がないため、催促のメール送信済み。→返信あり、お怒りでありMTGは２６日夕方しか開いていないとのこと。 日程調整のメール送付済み。回答をまつこととしたい。 MTGに向けて、西森さんは採用課題に対する現状分析の資料を作成し、当日提示する予定。→日程調整完了→5月26日15時から→MTG要旨、返金対象外に納得の上、支援に協力姿勢。法務対応はこれにてクローズとしたい(0526)', issue_details:'・チャットワーク入室遅延 受注3/23 ・メールアドレスの作成遅延→都度転送', contract_details:'第１０条第３項第２号', direction:'レッドカード', current_state:'・通知メール送信（5月11日済み） ↓ 先方からの反応待ち', ledger_url:'', contract_url:'https://drive.google.com/file/d/1MbYL0Ux1ao0CKeAoYaNEByXhq18El36v/view?usp=sharing', thread_url:'', email_slack_url:'https://docs.google.com/document/d/131FemH4A84e2PpQyrAWyrljQ1t5OuCzF1Kg1-7rE6qM/edit?tab=t.0', minutes_url:'', final_result:'返金対象外', closed_date:'2026/05/26' },
  { case_name:'サンマルコ株式会社', na_date:null, chief:'', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'通知メール送信(５月１１日済み)→返信待ち', issue_details:'・受注3/26 入室なし', contract_details:'第１０条第３項第２号', direction:'レッドカード', current_state:'・通知メール送信（5月11日済み） ↓ 先方からの反応待ち', ledger_url:'', contract_url:'https://drive.google.com/file/d/1LBJUzu6owKHevlLvr9qwUC4E0HN8cL2c/view?usp=sharing', thread_url:'', email_slack_url:'https://docs.google.com/document/d/1MA1Ia_jUzdEqh8DsaMZKyROsnlvCATwSWAKqdIHAW8c/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社サラダ介護', na_date:null, chief:'土井', status_phase:'MTGセット', ball:'クライアント', na_ledger:'通知メール確認中（5月11日） 再度、ファクト込めて再確認中(５月１２日)→社内確認中 0515南さん最終確認中→0515決裁完了→送信済み→返信ない場合督促  返信あり文案作成(0529)→送信済み、返信がきてMTGの日程を先方が提示するとのこと(0601)→MTG日程決定6月11日11時(0602)→MTG実施済み納得(0611)', issue_details:'チャットワーク入室遅延（作成2/10、入室3/5） メアド作成遅延（現在未作成）→完了4月17日 初回：3月30日 KOM：4月9日', contract_details:'', direction:'対象外でレッドカード', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1wozU4OqGxYMEog3Xg1tMS9b73crmf1Uh/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社レーベン', na_date:null, chief:'山本', status_phase:'先方対応中', ball:'クライアント', na_ledger:'・メール文作成→社内確認（0513）→メール送信済み(0513)通知メール送信 ※通知はステイ →役務停止の可能性あり 役務停止、３６協定、年間休日等の情報を精査する。 こちらから、コンタクトの必要あり。 ３６協定等共有あり役務再開MTG日程調整メール送信→送信済み(0519)加えてLINEとChatworkも送信済み(0519) 社労士と確認しているとのメールがあったため、返信済み(0520)→MTG実施し、社労士確認依頼→回答が来たため再度確認依頼(0602)', issue_details:'チャットワーク入室遅延 受注2/20 入出3/3　初回返事3/23 メアド作成遅延（現在未作成） 現在）テキストインタビュー待ち 初回：4月9日', contract_details:'第１０条第３項第１号及び第２号', direction:'法務相談で決定 イエローカードの方向 ↓ レッドカードに昇華（4月30日）', current_state:'・5月11日（月）に山本さん／志摩さんと方向性の確認', ledger_url:'', contract_url:'https://drive.google.com/file/d/1muP-fUWswxK19anZez77RJ0KSaI7IyTc/view?usp=sharing', thread_url:'', email_slack_url:'https://docs.google.com/document/d/11p9G8v4_e7HM4iCXkEFM14tHPBZFhQlyFHayrW8C1zA/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'日本エレベーター製造株式会社', na_date:null, chief:'土井', status_phase:'対象外合意形成済み', ball:'クライアント', na_ledger:'継続中→メール送信済み→返金対象外でクローズ', issue_details:'・媒体開設遅延 →採用活動に支障あり', contract_details:'', direction:'', current_state:'・4月20日に先方に2通目のメール送信 →返信なし（0421）', ledger_url:'', contract_url:'▼旧 https://drive.google.com/file/d/1ZkLo6RcJVP1wBpJ7Y67eeWlvWV1jltNP/view?usp=sharing  ▼新 https://drive.google.com/file/d/1zsXcqsQGqj0giRIjfQ6ZnggsBSx_gJRF/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A3AGJBNF6/p1775132649831459', email_slack_url:'https://docs.google.com/document/d/1ZcNT2pyJayEKnLqzL7hMRbft0B7AGKq4MXgpapGKt7Q/edit?tab=t.kfdw8m1yx3qk', minutes_url:'', final_result:'', closed_date:'2026/04/20' },
  { case_name:'株式会社NAKAMURA', na_date:null, chief:'土井', status_phase:'返金クローズ', ball:'完了', na_ledger:'返金でクローズ(0525) お願いベース対応 →志摩さん／平野で対応 メール作成済み→５月１２日送信済み 5月13日返信あり、MTGの日程調整の必要あり。 ↓ ５月１４日返信確認。 返金後再提案の流れになりそうだが、現場の再提案の材料収集等がある。 【MTG日程候補】  5月20日（水）10時～11時 5月21日（木）10時～12時 5月22日（金）10時～12時  これまでに再度、土井さんとのMTGセットする？ ※0514更新 日程再調整メール送信済み。回答を待つ ５月１５日返信あり、５月２５日以降の日程再調整を希望とのこと、返信対応したい。 また、南さん方針によると、月額再提案の筋でいくとのこと。留意されたい。 日程再調整のメール送信済み(0515)→返信がきて、MTGは返金後でかたくなな姿勢(0519)、社内に見解を求め中。  社内見解統一、返金にて本件クローズとなった(0522)', issue_details:'・非協力的', contract_details:'', direction:'法務的には厳しいが折衝の方向性', current_state:'', ledger_url:'', contract_url:'▼25卒 https://drive.google.com/file/d/1tROuSBUKxZLecGc9Jprbse-t4QPxTQNx/view?usp=sharing  ▼26卒 https://drive.google.com/file/d/1s7eI9tPDNR5CK4QbgMaCX_lNS2KKPpR_/view?usp=sharing', thread_url:'https://inrevohq.slack.com/archives/C0A71D5BWDV/p1775704528932229', email_slack_url:'https://docs.google.com/document/d/1MwDfOqMQQv1qpZRqv5kZKr761fHC8FdJ_OJxBnYahQU/edit?tab=t.0', minutes_url:'', final_result:'返金でクローズ', closed_date:'2026/05/31' },
  { case_name:'株式会社ALEXCEL', na_date:null, chief:'土井', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'メール確認OK（0512） ↓ 本日中に送信予定→送信済み(0512）', issue_details:'・168時間の依頼不通', contract_details:'第10条第3項第1号', direction:'レッドカード', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1rhq9lfCRvKLBxJvpSCXDpliGLnYF-7ov/view?usp=sharing', thread_url:'', email_slack_url:'https://docs.google.com/document/d/1Zy-f0tuUI1-2TWFVtH8CPJcDDq15SP3ggz3d-7M8NmE/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社ユーテム・プレシジョン', na_date:null, chief:'西森', status_phase:'返金クローズ', ball:'完了', na_ledger:'返金でクローズ', issue_details:'・168時間の依頼不通', contract_details:'', direction:'', current_state:'返金でクローズ 来季の新卒案件受注に向けて関係性継続狙い', ledger_url:'', contract_url:'https://drive.google.com/file/d/1KOLVX99liQrrx64sXzF0HEjfeXKZUqjq/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'返金でクローズ', closed_date:'2026/05/31' },
  { case_name:'株式会社新日本エネックス', na_date:null, chief:'土井', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'イエローカードの出し方考 ↓ レッドカードに昇華の可能性→法令違反による役務停止の線が浮上、現在法務精査中(0520)→役務停止で決着メール文案展開済みで決裁待ち(0525)→メール送付予定(0602)→メール送信済み(0602)', issue_details:'', contract_details:'', direction:'・イエローカード →契約取り消しの可能性？（5月11日）', current_state:'・現状スライド（4月10日）', ledger_url:'', contract_url:'https://drive.google.com/file/d/1QLpByTTEONYofywscCLlmYrrLCEEuJpa/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社ワンダーランド', na_date:null, chief:'', status_phase:'ステイ', ball:'様子見', na_ledger:'様子見（5月11日） 対象外事由がいったん消滅したため様子見。 今後も同様の事案が生じる可能性があるため本スプシには搭載', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1deU0c4gpEevHfaS71wb3AeA1Bdd9bZbX/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社レアル建設', na_date:null, chief:'柳川', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'通知メール送信 ※5月15日（金）の入金予定のため、それ以降にレッドカード→入金確認(０５１５) レッドカード文案作成後送信→レッドカード文案決裁中(05190953)→送信済み(05191106)', issue_details:'・168時間の連絡不通 ※4月15日→4月23日（音信不通） ※その間、何度か電話にて確認', contract_details:'第10条第3項第1号', direction:'・イエローカード →平野から先方へ ・入金遅延のためレッドカードへ ※4月30日予定が未入金', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1EIqq97dSWn0eNtelrgtHA-NGRyqOXo_m/view?usp=sharing', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'セーバー技研株式会社', na_date:null, chief:'西森', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'イエローカード →平野から先方へ ※通知メール送信（確認中） ※5月11日→５月１２日送信済み→5月19日現在の状況を西森さんに確認したところ、反応おそめではあるが対応は問題ないとのこと', issue_details:'遅延系', contract_details:'', direction:'・イエローカード', current_state:'', ledger_url:'', contract_url:'https://drive.google.com/file/d/1MgyIxQAJVtMznV2YycExVkAc8mvQBCPZ/view?usp=sharing', thread_url:'', email_slack_url:'https://docs.google.com/document/d/1p_lmdu0N1UDUA6N0mzyAedNl4xAzswZKwOf9OzvUjF8/edit?tab=t.0', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'ヒトツメ株式会社', na_date:'6月12日', chief:'西森', status_phase:'社内相談中', ball:'INREVO', na_ledger:'▼5月13日 メールを社内で確認中 5月14日西森さん回答待ち▼対象外連絡 こっちで対応 メール文案作成済み、平野さん確認中 ▼リファレンスチェック 西森さんで対応→西森さんに状況確認済み(05190923) 西森さんからの回答を踏まえて見解を共有、現在社内確認中。', issue_details:'同意のないリファレンスチェック', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'https://inrevohq.slack.com/archives/C0AK52L5F35/p1776337737337559', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社sizebook', na_date:null, chief:'山本', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行でクローズ。 山本さんから法務相談chにて状況報告をしてもらう（5月11日） ↓ 5月12日に擦り合わせ実施 状況的に厳しいかもしれない。一旦持ち帰りで回答（地藤さん） メール文案作成→決裁中(05190916)メール送信済み(05191054)→返信あり、代理人からの連絡が来る。法務移行でクローズ', issue_details:'', contract_details:'', direction:'', current_state:'・スラックにて報告待ち', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'法務移行', closed_date:'2026/05/19' },
  { case_name:'株式会社ピアズ', na_date:'6月17日', chief:'山本', status_phase:'MTGセット', ball:'クライアント', na_ledger:'法務相談ch確認→判断 ※5月11日 ↓ 地頭さん持ち帰り ※法令が絡むため要確認→山本先生の見解では職安法違反の疑いが強いため役務停止通知の方向性となった。誰が伝えるか、どう伝えるかのMTGを5月13日の14時30分よりセット。 ▼社内MTGセット 5月14日（木） 0830 山本さんから役務停止スラック投下・山本さん／成岡さんから、役務停止の連絡をスラックにて通達  ・志摩さんが◎◎労働局へ再度確認 ▼5月14日 志摩さんから厚生労働省へ問合せをして、中身の確認。 ※社名を伏せて問問合せ  ・それを踏まえ、メールにて詳細を送る ※5月14日に実施 ５月１５日８時４７分先方あてメール送信済み、期限は５月２２日まで、回答を待つこととしたい。 先方からMTG打診有、参加者は山本さん、成岡さん、藤原さん、法務的観点から避けるべきとアドバイス済み(0519) 先方から返信あり、メール文案作成中(0527)→送信済み(0528)→6月17日11時から社外MTG(0603)', issue_details:'①要配慮個人情報含むアンケートの実施 →選考で使用されていた イエローカード提出①_第7条に抵触 ②契約書にない選考基準で合否のジャッジを行っていた →イエローカード②_第10条に抵触 ③先方の対応が遅い →応募から面接設定まで1週間など →イエローカード③', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'東洋電興株式会社', na_date:null, chief:'柳川', status_phase:'ステイ', ball:'様子見', na_ledger:'5月12日MTG実施 ・柳川さんから返金オプション対象外となる旨案内 ・それでも立替拒否の場合方針決めMTG実施 ５月１２日、柳川さん架電も返金はけしからんとの回答、再度柳川さんからチャットワーク送信済み。 ↓ 立て替えOKをもらうための折衝を実施→OK とまっていた期間は延長できず…（0513確認）再度、柳川さんから止まっていた期間の延長を打診予定→進捗確認実施予定 柳川さんの折衝により、5月22日時点で、媒体の立替了承、よって返金対象外事由消滅。様子見としたい(0522)', issue_details:'①Indeed／エンプレの立て替え払い拒否', contract_details:'・14条３項に記載の通り、立替払いは応じなければならない規約となっている ・10条４項(9)に従い、役務提供に協力が得られず採用成果の創出を阻害', direction:'・返金対象外の処理でOK →立て替えOKの確認がとれた ※止まっていた期間の延長ができないと対象外となるため、再度折衝（柳川さん）', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'龍建設工業株式会社', na_date:null, chief:'', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'入金待ち後レッドカード→5月25日入金のため、6月2日レッドカード送付済み。', issue_details:'入金遅延', contract_details:'', direction:'対象外', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'日本スーパー工業', na_date:null, chief:'柳川', status_phase:'社内相談中', ball:'様子見', na_ledger:'先方は柳川さんんの上司とBC山本さんを合わせてMTGで説明を要求中。 対応協議の結果、ハロワ使用を伝えた事跡があるため、それを軸に交渉予定(5月15日)MTGセット及びMTGアサイン者決定→長野さん→長野さんから柳川さんへのFBあり、回答を待ち対応を検討0519→長野さんと柳川さんで支援の形構築中、いったんステータスは様子見に格下げ(0520)', issue_details:'不可媒体後出し(ハローワーク)', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'ウチヤマコーポレーション株式会社', na_date:null, chief:'土井', status_phase:'社内相談中', ball:'様子見', na_ledger:'見解をだして、社内確認中→対応方針検討中(0519)→なんとか説明を尽くして、定性面の契約違反可能性等を含めすり合わせとなった。法務としてはステータス様子見に格下げ(0520)土井さんがMTGで対応で決定', issue_details:'契約外の定性落とし。', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社エコプラスワン', na_date:null, chief:'山本', status_phase:'法務移行', ball:'完了', na_ledger:'法務移行で交渉クローズ。 内容精査中→脅迫まがいの連絡が先方からあり、事情を勘案しても対象外となるか。社内MTGセット済み(0520) MTGの結果、返金対象外でスタンスは変わらないがこちらの業務的な努力や考え方等を丁寧に説明する場を設け、その場で返金対象外を伝えつつ、せっかくヒットする求人ができたこともあり、返金相当額の月額充当で支援継続もカードに含めつつ対応することとなった。ステータスはINREVOに格上げ(0520)日程調整中(0521) 5月22日、先方はMTG実施拒否とのこと。志摩からメール送信となった。チャットワーク送信後、返信あり、MTG依頼があったため日程を含め返信した次なるMTGは5月29日16時から(0525)→見解書送付。', issue_details:'勝手に候補者対応', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'法務移行', closed_date:'2026/05/29' },
  { case_name:'株式会社共進ペイパー＆パッケージ', na_date:'6月12日', chief:'柳川', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'5月20日16：56投稿。事案発生日5月14日、5月22日志摩の見解を投下。返信等反応待ち。 柳川さんが先方と折衝中、対応如何によるため、推移を見守ることとしたい。 5月26日MTGセット→返金オプション外で結論、柳川さんから折衝→焦げ付いた場合は交渉人へ→焦げ付いたため、志摩からメール送信、メール文案決裁中(0603)→メール送信済み(0604)', issue_details:'5月14日に2次面接を実施した、中納 興希さんの見送り理由が「既に内定出ししている候補者との合否ラインを踏まえると、総合的に物足りないと判断」との理由で見送りとなりました。  お電話にて「今までの選考基準で見てもらえないか」ご相談したものの、すでに自社内で採用目標が達成できていることもあり、選考基準を変えることはできないとのこと。', contract_details:'第10条(返金規定) (5)当社の責めに帰すことができない事由により採用が中止となったためにまたはクライアントがヒトトレ 採用サービス外で採用を行ったためにヒトトレ採用保証プランでの採用ができなかった場合 10条第4項第5号及び同条同項4号、6号', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社フレスコ', na_date:'6月12日', chief:'米川', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'5月25日13時からMTGを実施。→方針決定MTGに進むこととなった→いったんステイ(0526)→６月１日１６時から社内交渉方針決定MTG(0528)→志摩からメール送信で決定メール文案決裁中(0603)→米川さんのあいさつを待って送信。→メール送信済み0605→延長及び媒体の打診について確認予定(0608)', issue_details:'契約書外', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'D＆I', na_date:'6月16日', chief:'西森', status_phase:'MTGセット', ball:'様子見', na_ledger:'MTGセット完了→6月9日', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
  { case_name:'株式会社M&U agency様', na_date:null, chief:'土井', status_phase:'見解送付済み', ball:'クライアント', na_ledger:'返信あり、内容確認後文案作成。→文案のたたきは完了しているが数値の回収を土井さんに依頼中→メール決裁中(0605)→メール送信済み(0608)', issue_details:'', contract_details:'', direction:'', current_state:'', ledger_url:'', contract_url:'', thread_url:'', email_slack_url:'', minutes_url:'', final_result:'', closed_date:null },
];

async function main() {
  console.log(`[legal-import] team_id=${TEAM_ID}, cases=${CASES.length}`);

  // 既存案件名のセット取得（重複防止）
  const { rows: existing } = await dbQuery(
    `SELECT case_name FROM legal_cases WHERE team_id=$1`, [TEAM_ID]
  );
  const existingSet = new Set(existing.map(r => (r.case_name || '').trim()));

  let inserted = 0, skipped = 0;
  for (const c of CASES) {
    if (existingSet.has(c.case_name.trim())) {
      skipped++;
      continue;
    }
    const naDate = parseJpDate(c.na_date);
    const closedDate = parseJpDate(c.closed_date);
    const result = c.final_result || '対応中'; // 既存の result カラム互換のため

    try {
      await dbQuery(
        `INSERT INTO legal_cases (
          team_id, case_name, na_date, chief, ball, na_ledger,
          issue_details, contract_details, direction,
          status_phase, current_state, ledger_url, contract_url,
          thread_url, email_slack_url, minutes_url,
          final_result, closed_date, result, priority
        ) VALUES (
          $1, $2, $3, $4, $5, $6,
          $7, $8, $9,
          $10, $11, $12, $13,
          $14, $15, $16,
          $17, $18, $19, $20
        )`,
        [
          TEAM_ID, c.case_name, naDate, c.chief || null, c.ball || null, c.na_ledger || null,
          c.issue_details || null, c.contract_details || null, c.direction || null,
          c.status_phase || null, c.current_state || null, c.ledger_url || null, c.contract_url || null,
          c.thread_url || null, c.email_slack_url || null, c.minutes_url || null,
          c.final_result || null, closedDate, result, '中',
        ]
      );
      inserted++;
      console.log(`  + ${c.case_name}`);
    } catch (e) {
      console.error(`  ! ${c.case_name}:`, e.message);
    }
  }
  console.log(`[legal-import] done. inserted=${inserted}, skipped=${skipped}`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
